feat(chart): bump Chart version to support proxy-protocol
camptocamp/devops-stack-module-traefik pull request #16
Opened 2022-11-22 12:49 UTC by Xaving

The chart version v16.2.0 supports proxy protocol
Until now it was possible to do it with CLI
The version of the application stay unchanged

This was tested on a scaleway simplify DEVOPS.
A middlewareTCP with whitelist IP's can be instantiated and attached to a route.

2022-11-23 08:06 UTC, jbarascut approved these changes

2022-11-23 08:41 UTC, lentidas requested changes
Concerning the chart: hasn't it been decided that from now on we ship all the charts as a tgz instead of extracting the chart?

Still, the PR includes the 2 versions. Is there a problem with that?

2022-11-23 08:43 UTC, lentidas commented
Do not forget to add the comment `Release-As: v1.0.0-alpha.2` otherwise release please will bump the release to v1.0.0 automatically. Just something to keep in mind before merging.

2022-12-04 19:12 UTC, lentidas approved these changes

2022-12-05 07:04 UTC, merged