feat(main): introduce a variable to set autosync
camptocamp/devops-stack-module-traefik pull request #25
Opened 2022-12-07 09:10 UTC by Xaving

autosync is set to false by default

This feature has been test on scaleway instance

2022-12-08 10:53 UTC, cryptobioz commented on variables.tf
> +  type = bool
I do agree it would be a better long term solution. However, in the day to day operations, we just want to be able to activate or deactivate the autosync feature. I'd suggest to first add this functionality and implement later (if we really needs it) the possibility to configure all the options.

2022-12-08 15:35 UTC, modridi commented on variables.tf
> +  type = bool
If you must. But please make sure you set the default back to true before you merge.

2022-12-09 08:27 UTC, lentidas requested changes

2022-12-09 08:27 UTC, lentidas commented on variables.tf
> +
Wouldn't it be better if we pass a proper Terraform variable instead of using a boolean that activates a local variable?

```suggestion
variable "app_autosync" {
  type = map(object({
    allow_empty = bool
    prune = bool
    self_heal = bool
  }))
  default = {
    allow_empty = false
    prune = true
    self_heal = true
  }
}
```

The inconvenient with this approach is that in the event someone wants to deactivate the autosync is that they will be forced to declare the entire object in the module instantiation but at least it will be clearer. Otherwise as a bare minimum I would put a description in the variable saying what the variable activates in the locals. And I agree with @modridi, the variable should default as true, as I pointed out during the weekly (I do not know if you decided anything after I left).

2022-12-09 09:49 UTC, lentidas commented on variables.tf
> +
After discussion, we'll leave this as-is for know, because the changes are urgently needed for Scaleway.

2022-12-09 09:50 UTC, lentidas commented on variables.tf
> +  type = bool
Since the default is as true, we'll no longer block this merge for now.

2022-12-09 09:58 UTC, modridi approved these changes

2022-12-09 10:22 UTC, merged