fix(main): enrich autosync var and default to true
camptocamp/devops-stack-module-traefik pull request #28
Opened 2022-12-09 17:02 UTC by Xaving

This has been tested on scaleway

2022-12-12 08:20 UTC, lentidas requested changes

2022-12-12 08:20 UTC, lentidas commented on variables.tf
> +  description = "Autosync option configuration for argocd application"
```suggestion
  description = "Automated sync options for the Argo CD Application resource."
```

2022-12-13 20:07 UTC, lentidas approved these changes

2022-12-14 11:07 UTC, cryptobioz approved these changes

2022-12-14 12:20 UTC, merged