Isdevops 214 monitoring
camptocamp/devops-stack-module-traefik pull request #41
Opened 2023-05-11 15:56 UTC by ckaenzig

## Description of the changes

Enable monitoring in chart and add a dashboard. Choice of dashboard needs to be discussed.

This PR depends on:

- [ ] #40

## Breaking change

- [x] No

## Tests executed on which distribution(s)

- [ ] KinD
- [ ] AKS (Azure)
- [ ] EKS (AWS)
- [ ] Scaleway
- [ ] SKS (Exoscale)

2023-05-12 06:14 UTC, lentidas requested changes

2023-05-12 06:14 UTC, lentidas commented on locals.tf
> +            enabled = true
I propose you add the variable you proposed on the `cert-manager` module.

2023-05-12 06:14 UTC, lentidas commented on variables.tf
> +  description = "Number of traefik pods"
```suggestion
  description = "Number of Traefik pods to be deployed."
```

2023-05-12 07:20 UTC, ckaenzig commented on locals.tf
> +            enabled = true
Yep, good point :+1:

2023-05-12 07:21 UTC, ckaenzig commented on variables.tf
> +  description = "Number of traefik pods"
This PR will be rebased on main after #40 is merges.

2023-05-15 07:54 UTC, ckaenzig commented
PR rebased on main. Still need to test the grafana dashboard and review infos by Mohamed.

2023-05-16 13:51 UTC, ckaenzig commented
Converting back to draft because the dashboard doesn't work in another cluster than first tested, probably because of hard-coded datasource UIDs. To be investigated.

2023-05-17 08:50 UTC, lentidas requested changes

2023-05-17 08:50 UTC, lentidas commented on locals.tf
> +            foo = "bar"
I don't understand the line `foo = bar`. Is it just to have a value set in the `values.yaml` in order to activate the dashboard or am I misunderstanding?

2023-05-17 08:50 UTC, lentidas commented on variables.tf
> +  description = "Enable prometheus ServiceMonitor in helm chart."
```suggestion
  description = "Enable Prometheus ServiceMonitor in the Helm chart."
```

2023-05-17 11:11 UTC, ckaenzig commented on locals.tf
> +            foo = "bar"
Yes, `var.enable_service_monitor` needs to evaluate to `true` in the helm chart, but we don't need to set any value in it. I put `enabled = true` initially, but that would make people thing that the `enable` value would be used in the chart.

2023-05-17 11:25 UTC, lentidas commented on locals.tf
> +            foo = "bar"
That's what I thought. I agree that putting `enabled = true` could induce someone into error. Maybe just add a small comment on the side so we do not forget the reason for this?

2023-05-22 09:26 UTC, merged